### ISSUE TITLE
When a track has an emoji in the title, then the emoji will stay on the title of subsequent tracks

### ISSUE THREAD

**Issue by edofe99** [audacious-media-player/audacious#1491] opened 2024-10-14 16:42 UTC
**Steps to reproduce**
How and when does the bug occur?
1. Open a folder that has multiple tracks and one of them with an emoji in the title.
2. Play the track with the emoji
3. Skip to another track
4. You'll see that the GUI will glitch with the emoji.

**Comment by radioactiveman** [comment] 2024-10-15 18:30
I can't reproduce this issue with the given steps.

Please fill out all the information originally asked in the issue template. We also need a screenshot or screencast to understand what you mean with "glitch".

**Comment by ironhak** [comment] 2024-10-15 19:38
https://github.com/user-attachments/assets/c58dc53a-bd80-47b8-bc0c-fc88c251eb1c

Example

**Comment by radioactiveman** [comment] 2024-10-16 23:16
Thanks, I was able to reproduce it now after installing `noto-fonts-emoji` with the GTK interface (GTK version 2 and 3).

**Comment by radioactiveman** [comment] 2024-10-21 21:33
Fixed with https://github.com/audacious-media-player/audacious-plugins/commit/ac482565142ad7dca712d00f89da08f57d6733c7 from https://github.com/audacious-media-player/audacious-plugins/pull/171.

**Closed by radioactiveman** 2024-10-21 21:33 UTC
Labels: Bug
