### ISSUE TITLE
Erroring on attempting to read/write metadata on .mp3s

### ISSUE THREAD

**Issue by CaptainD54321** [audacious-media-player/audacious#1465] opened 2024-09-09 02:20 UTC
**Describe the bug**
I've been attempting to switch to Audacious as my music player because it seems better than the one that came preinstalled with my distro, but its currently having trouble reading or editing the metadata on some mp3 songs I just downloaded. See attached log (lightly edited to hide specific irrelevant personal information, i.e. my username and the exact song) for log output from doing the following:
1. Start audacious with `audacious -V`
2. Select and start playing the playlist for the album I've been attempting to fix the metadata on
3. Right-click and select "Song Info" for the first song in the playlist
4. Enter metadata into song info window and click Save
5. Window says "Save Error"
6. Close Audacious

**Additional information**
* Audacious 4.1 GTK version
* Linux Mint 21.3 Cinnamon

[audacious.log](https://github.com/user-attachments/files/16924643/audacious.log)

**Comment by radioactiveman** [comment] 2024-09-20 19:09
The log messages imply that the file is not a MP3 file. Such files should also not be handled by the `ffaudio` plugin but `madplug`.
What is its extension and mime type? Check it with `file --mime-type file.mp3`.

```
INFO ffaudio-core.cc:263 [get_format_by_extension]: Matched format mov,mp4,m4a,3gp,3g2,mj2 by extension.
```

Your Audacious version is also very old, released in 2021. See https://audacious-media-player.org/download for instructions.

**Comment by radioactiveman** [comment] 2024-10-11 11:34
Not a bug, using an outdated Audacious version and no further response. Closing.

**Closed by radioactiveman** 2024-10-11 11:34 UTC
Labels: Bug
