### ISSUE TITLE
Audacious fails to start on pure Wayland system with error about Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by knm100** [audacious-media-player/audacious#1403] opened 2024-06-07 07:48 UTC
**Describe the bug**
audacious-git-1:4.4.beta1.r12.gc684358a1 can't run in a pure qt6 environment（without any qt5 package)
but audacious-git-1-4.4.beta1.r0.gc7539c5bb can work fine.

**Steps to reproduce**
in a pure qt6 environment(without any qt5 package),  run audacious-git-1:4.4.beta1.r12.gc684358a1 
How and when does the bug occur?
audacious-git-1:4.4.beta1.r12.gc684358a1  can't be started, Clicking on the icon doesn't do anything.
in a terminal, output following message:
from 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
**Expected behavior**
What do you expect to happen instead?
I hope the audacious-git-1:4.4.beta1.r12.gc684358a1 can run in the pure qt6 environment as like audacious-git-1-4.4.beta1.r0.gc7539c5bb 
**Additional information**
I confirm that audacious-git-1-4.4.beta1.r0.gc7539c5bb can work fine.
* Audacious version and interface (Qt / GTK / Winamp)
audacious-git-1:4.4.beta1.r12.gc684358a1 with qt6 interface
* Operating system and version
 Arch linux
* Desktop environment
LXQT2.0.1(wayland session)+labwc 0.72
* Screenshots
no
* Sample files
no
* Logs (use `LANG=C audacious -V` for English output)
no

**Comment by radioactiveman** [comment] 2024-06-07 10:24
This should not be related to Qt 5, my guess is commit https://github.com/audacious-media-player/audacious/commit/334a8ef6d0c3266e5fa08e6c0bd2cc8f9085bb01 instead.

Please check/answer:
- Start Audacious with `export QT_QPA_PLATFORM=wayland audacious`. This should work for you.
- Start another Qt based application with "export QT_QPA_PLATFORM=xcb" to see if the Qt xcb plugin can't be loaded in general.
- Do you use `qt6-base` from Arch repositories or a customized self-built version?
- Is `libxcb` installed?

@jlindgren90: IIRC you also use Arch with LXQt and even contribute to labwc. Do you have more ideas and can you reproduce the error?

**Comment by knm100** [comment] 2024-06-07 10:54
>Does Audacious start now after installing qt5-base or is this only your guess that Qt 5 is required?


I have no try on qt5,  but chromium have the same issue,  qt5-base installed  can fix it.

>Start Audacious with export QT_QPA_PLATFORM=wayland audacious. This should work for you.


i got the same output message with QT_QPA_PLATFORM=wayland

>Start another Qt based application with "export QT_QPA_PLATFORM=xcb" to see if the Qt xcb plugin can't be loaded in general.


 i compiled the labwc without xwayland, So QT_QPA_PLATFORM=xcb  shoulde not  work.

>Do you use qt6-base from Arch repositories or a customized self-built version?


my qt6-base is form offical package,  it was  installe  as as a dependency package  with pacman -S  lxqt 

>Is libxcb installed?


Pretty sure,  because the libxcb and xcb-util-cursor  are  dependency packages of qt6-base.

**Comment by radioactiveman** [comment] 2024-06-07 17:17
> I have no try on qt5, but chromium have the same issue, qt5-base installed can fix it.

Audacious does not depend on Qt 5, at least since Audacious 4.4.

> i got the same output message with QT_QPA_PLATFORM=wayland

Please post the full output, I doubt it is exactly the same with "wayland" and "xcb". The command should not include "export", it was wrong in the post above.

`QT_QPA_PLATFORM=wayland audacious`

**Comment by knm100** [comment] 2024-06-08 02:15
after  export QT_QPA_PLATFORM=wayland ,  audacious-git-1:4.4.beta1.r12.gc684358a1  can be started without any message.
I wonder  why don't audacious-git-1-4.4.beta1.r0.gc7539c5bb need "export QT_QPA_PLATFORM=wayland".
if the rev .r0.gc7539c5bb  can automatically detect whether the QT platform is wayland or XCB
but  Rev r12.gc684358a1  can‘t do it.

**Comment by knm100** [comment] 2024-06-08 03:18
In the GTK interface, it also cannot be started, and the output information is as follows
![Uploading swappy-20240608-110648.png…]()

**Comment by knm100** [comment] 2024-06-08 05:07
Assuming Rev 4.4.beta1.r12.gc684358a1 runs itself on xwayland or xorg by default, then QT_QPA_PLATFORM=wayland should be specified because my labwc is wayland only.   but why it need QT_QPA_PLATFORM=wayland in LXQT2.0.1+KWIN?
In Arch, installing KWIN will automatically install xorg and xwayland as dependencies.
And qt6 itself doesn't need to specify QT_QPA_PLATFORM like QT5.

**Comment by jlindgren90** [comment] 2024-06-08 15:34
Using XWayland instead of native Wayland was intentional. However the error messages are a bit confusing when XWayland is not available.

@radioactiveman do you have any ideas how we should handle this case?

**Comment by jlindgren90** [comment] 2024-06-08 15:36
Maybe we print an error and exit if DISPLAY is unset, and the variables to explicitly enable Wayland backends are not set?

**Comment by radioactiveman** [comment] 2024-06-08 16:50
The drawback of our current approach is that no error dialog at all is shown for GUI users. And the error message by Qt on the command line is probably more confusing than helpful for most users.

Would it be possible to do something like this?
1. Ask Wayland users on first start of Audacious if Wayland should be used continuously, with an explanation why we do not recommend that and what does not work (Winamp interface, hotkeys plugin, docking of plugin windows, ...)
2. Save the answer as bool for libaudqt/libaudgui
3. Check it in early initialization of libaudqt/libaudgui to set the env variables for XWayland if required
(4.) Include a checkbox in the settings dialog?

Checking for Wayland based on environment variables is unreliable. Checking it later with Qt/GTK (like we do in some plugins already) should be safe.

I'm not sure though if it is possible to handle all that in libaudqt/libaudgui alone or the interface plugins need to be adjusted as well. And if a user on Wayland has no XWayland option but enables it, he still has the issue after the next restart.

**Comment by jlindgren90** [comment] 2024-06-08 17:03
I would like to continue defaulting to XWayland automatically if it's available. If not (DISPLAY is unset), a warning dialog with an "I understand and promise not to report any bugs" checkbox seems reasonable.

**Comment by radioactiveman** [comment] 2024-06-08 17:17
> defaulting to XWayland automatically if it's available.

I don't get it how we can check that. We may detect with `WAYLAND_DISPLAY` / `DISPLAY` / `XDG_SESSION_TYPE` if X11 or Wayland is used. But not if XWayland is supported by the window manager and Qt/GTK.

- https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used
- https://stackoverflow.com/questions/45536141/how-i-can-find-out-if-a-linux-system-uses-wayland-or-x11

**Comment by jlindgren90** [comment] 2024-06-08 17:35
If XWayland is unavailable then I would expect DISPLAY to be unset. It would be good to verify this.

**Comment by knm100** [comment] 2024-06-09 02:03
> If XWayland is unavailable then I would expect DISPLAY to be unset. It would be good to verify this.
You've done it in r0.gc7539c5bb.

 @radioactiveman please see the following: 
LXQT+labwc(My labwc is wayland only, so the $DISPLAY  is unset)
![LXQT-labwc](https://github.com/audacious-media-player/audacious/assets/166389780/c0e8f034-3353-4cf7-9797-57b176e38e0b)


LXQt+Kwin

**Comment by knm100** [comment] 2024-06-09 02:34
>In Arch, installing KWIN will automatically install xorg and xwayland as dependencies.
And qt6 itself doesn't need to specify QT_QPA_PLATFORM like QT5.

I'm sorry,  I forgeted that I get my kwin run on  wayland only.  after added xwayland,    Rev  r12.gc684358a1 can't run on xwayland without Any other additional variable.

If you want Audacious to end up running under Wayland, you need to be bold enough to make it work under Wayland by default, and only move to Xwayland if there's a problem with Wayland


At least it doesn't require the user to set the wayland environment variable in system-wide (which is anachronistic today), maybe you can refer to chromium, Set the wayland or xwayland in  it‘s configuration file or in the GUI

**Comment by jlindgren90** [comment] 2024-06-09 03:15
2fae5c12c4a562cb597bcfa7c7770d4a4367095d should help. I tested it here under labwc with DISPLAY unset, and Audacious starts up using native Wayland now (with a warning) in both GTK and Qt modes.

@radioactiveman please feel free to improve on the warning if you like (add more explanation, make it a GUI popup, etc.), but I figured this was better than nothing :)

**Comment by knm100** [comment] 2024-06-09 04:53
thank you,  it is fine for me.

**Comment by radioactiveman** [comment] 2024-06-09 20:50
> please feel free to improve on the warning

It was missing the new-line character, fixed now in master.

> thank you, it is fine for me.

Same for me, I think we can close this issue now.

**Closed by radioactiveman** 2024-06-09 20:50 UTC
Labels: Bug
